micronaut:
  application:
    name: crudCompetencias
netty:
  default:
    allocator:
      max-order: 3


datasources:
  default:
    name: 'postgres4'
    username: 'postgres'
    password: 'postgres'
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

